name: Tag Latest

on:
  release:
    types: [published]

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - name: Update latest
        run: |
          git fetch --unshallow --tags

          git tag --list

          git checkout ${GITHUB_REF#refs/*/}
          git tag -d latest
          git tag latest
          git push origin :latest
          git push origin latest

      - name: Post webhook
        run: |
          curl -X POST ${{ secrets.OCP_GENERIC_WEBHOOK }}
