name: Tag Latest

on:
  release:
    types: [published]

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        # with:
        #   ref: ${{ GITHUB_REF }}
      - run: |
          echo "$GITHUB_REF"
